spring:
  cloud:
    gcp:
      project-id: AAA
  profiles:
    active: default
server:
  port: 8090
  tomcat:
    basedir: caas_base
    accesslog:
      enabled: false
      pattern: '%t %a "%r" %s (%D ms)'
      suffix: '.log'
      directory: access_logs
      pubsub:
        push:
          enabled: false
project:
  env: default
  gcp:
    credentials: '{"type": "AAAA","project_id": "AAA","private_key_id": "AAAA","private_key": "AAA"}'
  log:
    path: './local-logs'
    archive:
      clean:
        days: 2  
    app:
      rollover: '1'
      size: '10 MB'
      level: 'DEBUG'
    lib:
      rollover: '1'
      size: '10 MB'
      level: 'INFO'
management:
  security:
    enabled: false
  health:
    jms:
      enabled: false
    rabbit:
      enabled: false
