spring:
  application:
    name: spring-google
  jackson:
    serialization-inclusion: NON_EMPTY
server:
  contextPath: /api/spring/google
endpoints:
  health:
    sensitive: false
    time-to-live: 100
project:
  group: core
  team: content
  application: 'spring-google' 